title: <p align="center"> Ganesh Babu G </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ganeshbabug/">LinkedIn</a> |
  <a href="https://github.com/ganeshbabunn">GitHub</a>
 
  <br>  
  I'm passion is towards working in Data science(ML,DL,NLP).
  I worked in Business-Data Analyst/Software Development/Enterpise Architect/Project maangement
  <br>
  </p>


theme: jekyll-theme-minimal
