title: <p align="center"> Ganesh Babu G </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ganeshbabu/">LinkedIn</a> |
  <a href="https://github.com/ganeshbabunn">GitHub</a>
 
  <br>  
  I'm passion towards Data science(ML,DL,NLP).
  I worked before in Business analyst/Data Analyst/Software Development/Enterpise Solution Architect/Project management 
  from the projects varies from Manufacturing,Service,Finance,Supply chain,Operations in Healthcare domain.
  I am Currently working as Project lead in SDTM domain.
  <br>
  </p>


theme: jekyll-theme-minimal
