title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ganeshbabug/">LinkedIn</a> |
  <a href="https://github.com/ganeshbabunn">GitHub</a>
 
  <br>  
  I'm passion is towards Data science wokring towards ML,AI and NLP.
  I worked in Business-Data Analyst/Software Development/Enterpise Architect/Project maangement
  <br>
  </p>



theme: jekyll-theme-minimal
